import { useState, useRef, useCallback, useEffect } from 'react';
import { Header } from '@/components/Header';
import { UploadZone } from '@/components/UploadZone';
import { MediaPlayer, MediaPlayerRef } from '@/components/MediaPlayer';
import { SubtitleList } from '@/components/SubtitleList';
import { Timeline } from '@/components/Timeline';
import { EditSubtitleDialog } from '@/components/EditSubtitleDialog';
import { AutoGenerateDialog } from '@/components/AutoGenerateDialog';
import { TranslateDialog } from '@/components/TranslateDialog';
import { ExportVideoDialog } from '@/components/ExportVideoDialog';
import { ExportSubtitleDialog } from '@/components/ExportSubtitleDialog';
import { SettingsDialog } from '@/components/SettingsDialog';
import { parseSubtitleFile, type Subtitle } from '@/lib/subtitleParser';
import { type TranslatedSubtitle } from '@/lib/translationService';
import { defaultSubtitleStyle, type SubtitleStyle } from '@/components/SubtitleStyleSettings';
import { useSubtitleHistory } from '@/hooks/useSubtitleHistory';
import { Download, Trash2, Wand2, Upload, Languages, Film, FileText, Settings } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';

const Index = () => {
  const [mediaFile, setMediaFile] = useState<{ url: string; name: string; type: 'video' | 'audio'; file: File } | null>(null);
  const [subtitleFileName, setSubtitleFileName] = useState<string>('');
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [editingSubtitle, setEditingSubtitle] = useState<Subtitle | null>(null);
  const [showAutoGenerate, setShowAutoGenerate] = useState(false);
  const [showTranslate, setShowTranslate] = useState(false);
  const [showExportVideo, setShowExportVideo] = useState(false);
  const [showExportSubtitle, setShowExportSubtitle] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [subtitleStyle, setSubtitleStyle] = useState<SubtitleStyle>(defaultSubtitleStyle);
  const [selectedSubtitleId, setSelectedSubtitleId] = useState<number | null>(null);
  const playerRef = useRef<MediaPlayerRef>(null);

  // Use subtitle history hook for undo/redo
  const {
    subtitles,
    setSubtitles,
    setSubtitlesWithoutHistory,
    resetHistory,
    undo,
    redo,
    canUndo,
    canRedo,
    clipboard,
    copySubtitle,
    pasteSubtitle,
    insertSubtitle,
    deleteSubtitle,
  } = useSubtitleHistory([]);

  // Check if subtitles have translations
  const hasTranslation = subtitles.some(sub => 'translatedText' in sub && sub.translatedText);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't trigger shortcuts when typing in input fields
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) {
        return;
      }

      // Ctrl/Cmd + Z: Undo
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) {
        e.preventDefault();
        undo();
      }
      // Ctrl/Cmd + Y or Ctrl/Cmd + Shift + Z: Redo
      if ((e.ctrlKey || e.metaKey) && (e.key === 'y' || (e.key === 'z' && e.shiftKey))) {
        e.preventDefault();
        redo();
      }
      // Ctrl/Cmd + C: Copy
      if ((e.ctrlKey || e.metaKey) && e.key === 'c' && selectedSubtitleId) {
        const sub = subtitles.find(s => s.id === selectedSubtitleId);
        if (sub) {
          e.preventDefault();
          copySubtitle(sub);
          toast.success('已复制字幕');
        }
      }
      // Ctrl/Cmd + V: Paste
      if ((e.ctrlKey || e.metaKey) && e.key === 'v' && clipboard) {
        e.preventDefault();
        pasteSubtitle(selectedSubtitleId ?? undefined);
        toast.success('已粘贴字幕');
      }
      // Delete or Backspace: Delete selected
      if ((e.key === 'Delete' || e.key === 'Backspace') && selectedSubtitleId) {
        e.preventDefault();
        deleteSubtitle(selectedSubtitleId);
        setSelectedSubtitleId(null);
        toast.success('已删除字幕');
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [undo, redo, copySubtitle, pasteSubtitle, deleteSubtitle, selectedSubtitleId, subtitles, clipboard]);

  const handleMediaUpload = useCallback((file: File) => {
    const url = URL.createObjectURL(file);
    const type = file.type.startsWith('video') ? 'video' : 'audio';
    setMediaFile({ url, name: file.name, type, file });
    toast.success(`已加载: ${file.name}`);
  }, []);

  const handleSubtitleUpload = useCallback((file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      const parsed = parseSubtitleFile(content, file.name);
      resetHistory(parsed);
      setSubtitleFileName(file.name);
      toast.success(`已加载 ${parsed.length} 条字幕`);
    };
    reader.readAsText(file);
  }, [resetHistory]);

  const handleSeek = useCallback((time: number) => {
    playerRef.current?.seek(time);
    setCurrentTime(time);
  }, []);

  const handleEditSubtitle = useCallback((subtitle: Subtitle) => {
    setEditingSubtitle(subtitle);
  }, []);

  const handleSaveSubtitle = useCallback((updatedSubtitle: Subtitle) => {
    setSubtitles(prev => 
      prev.map(sub => sub.id === updatedSubtitle.id ? updatedSubtitle : sub)
    );
    toast.success('字幕已更新');
  }, [setSubtitles]);

  const handleAutoGeneratedSubtitles = useCallback((newSubtitles: Subtitle[]) => {
    resetHistory(newSubtitles);
    setSubtitleFileName('AI生成字幕');
  }, [resetHistory]);

  const handleSubtitleTimeChange = useCallback((id: number, startTime: number, endTime: number) => {
    setSubtitlesWithoutHistory(prev => 
      prev.map(sub => sub.id === id ? { ...sub, startTime, endTime } : sub)
    );
  }, [setSubtitlesWithoutHistory]);

  const handleInsert = useCallback((afterTime: number) => {
    insertSubtitle(afterTime);
    toast.success('已插入新字幕');
  }, [insertSubtitle]);

  const handleCopy = useCallback((subtitle: TranslatedSubtitle) => {
    copySubtitle(subtitle);
    toast.success('已复制字幕');
  }, [copySubtitle]);

  const handlePaste = useCallback((afterId?: number) => {
    if (clipboard) {
      pasteSubtitle(afterId);
      toast.success('已粘贴字幕');
    }
  }, [clipboard, pasteSubtitle]);

  const handleDelete = useCallback((id: number) => {
    deleteSubtitle(id);
    if (selectedSubtitleId === id) {
      setSelectedSubtitleId(null);
    }
    toast.success('已删除字幕');
  }, [deleteSubtitle, selectedSubtitleId]);

  const handleTranslated = useCallback((translatedSubtitles: TranslatedSubtitle[]) => {
    setSubtitles(translatedSubtitles);
  }, [setSubtitles]);

  const handleClearAll = useCallback(() => {
    if (mediaFile?.url) URL.revokeObjectURL(mediaFile.url);
    setMediaFile(null);
    resetHistory([]);
    setSubtitleFileName('');
    setCurrentTime(0);
    setDuration(0);
    setIsPlaying(false);
    setSelectedSubtitleId(null);
    toast.info('已清除所有内容');
  }, [mediaFile, resetHistory]);

  return (
    <div className="min-h-screen bg-background">
      <Header onOpenSettings={() => setShowSettings(true)} />
      
      <main className="container mx-auto px-4 py-8">
        {/* Upload Section */}
        {!mediaFile && (
          <div className="max-w-4xl mx-auto animate-fade-in">
            <div className="text-center mb-8">
              <h2 className="text-3xl font-bold gradient-text mb-2">开始创作</h2>
              <p className="text-muted-foreground">上传您的媒体文件和字幕，或使用AI自动生成</p>
            </div>
            
            <div className="grid md:grid-cols-2 gap-6">
              <UploadZone
                type="media"
                onFileSelect={handleMediaUpload}
                accept="video/mp4,video/webm,audio/mp3,audio/mpeg,audio/wav"
              />
              <UploadZone
                type="subtitle"
                onFileSelect={handleSubtitleUpload}
                accept=".srt,.vtt"
                currentFile={subtitleFileName}
              />
            </div>
          </div>
        )}

        {/* Editor Section */}
        {mediaFile && (
          <div className="animate-fade-in">
            {/* Action buttons */}
            <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
              <div className="flex items-center gap-2">
                <span className="text-sm text-muted-foreground">正在编辑:</span>
                <span className="px-3 py-1 rounded-lg bg-secondary text-foreground font-medium">
                  {mediaFile.name}
                </span>
              </div>
              
              <div className="flex items-center gap-2 flex-wrap">
                {/* Settings Button */}
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowSettings(true)}
                  className="gap-2"
                >
                  <Settings className="w-4 h-4" />
                  设置
                </Button>

                {/* AI Generate Button */}
                <Button
                  variant="default"
                  size="sm"
                  onClick={() => setShowAutoGenerate(true)}
                  className="gap-2 bg-gradient-to-r from-primary to-accent hover:opacity-90"
                >
                  <Wand2 className="w-4 h-4" />
                  AI 生成字幕
                </Button>

                {/* Translate Button */}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowTranslate(true)}
                  disabled={subtitles.length === 0}
                  className="gap-2"
                >
                  <Languages className="w-4 h-4" />
                  翻译字幕
                </Button>
                
                {/* Upload subtitle */}
                <label className="cursor-pointer">
                  <input
                    type="file"
                    accept=".srt,.vtt"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleSubtitleUpload(file);
                    }}
                    className="hidden"
                  />
                  <Button variant="outline" size="sm" className="gap-2" asChild>
                    <span>
                      <Upload className="w-4 h-4" />
                      上传字幕
                    </span>
                  </Button>
                </label>
                
                {/* Export Dropdown */}
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={subtitles.length === 0 && mediaFile?.type !== 'video'}
                      className="gap-2"
                    >
                      <Download className="w-4 h-4" />
                      导出
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-48">
                    <DropdownMenuItem 
                      onClick={() => setShowExportSubtitle(true)}
                      disabled={subtitles.length === 0}
                      className="gap-2"
                    >
                      <FileText className="w-4 h-4" />
                      导出字幕文件
                    </DropdownMenuItem>
                    <DropdownMenuItem 
                      onClick={() => setShowExportVideo(true)}
                      disabled={mediaFile?.type !== 'video' || subtitles.length === 0}
                      className="gap-2"
                    >
                      <Film className="w-4 h-4" />
                      导出带字幕视频
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>

                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleClearAll}
                  className="gap-2 text-destructive hover:text-destructive"
                >
                  <Trash2 className="w-4 h-4" />
                  清除
                </Button>
              </div>
            </div>

            {/* Main editor layout */}
            <div className="grid lg:grid-cols-3 gap-6">
              {/* Player column */}
              <div className="lg:col-span-2 space-y-4">
                <MediaPlayer
                  ref={playerRef}
                  src={mediaFile.url}
                  type={mediaFile.type}
                  subtitles={subtitles}
                  currentTime={currentTime}
                  onTimeUpdate={setCurrentTime}
                  onDurationChange={setDuration}
                  isPlaying={isPlaying}
                  onPlayPause={() => setIsPlaying(!isPlaying)}
                  subtitleStyle={subtitleStyle}
                  onSubtitleStyleChange={setSubtitleStyle}
                  hasTranslation={hasTranslation}
                />
                
                <Timeline
                  subtitles={subtitles}
                  duration={duration}
                  currentTime={currentTime}
                  onSeek={handleSeek}
                  onSubtitleChange={handleSubtitleTimeChange}
                  onInsert={handleInsert}
                  onCopy={handleCopy}
                  onPaste={handlePaste}
                  onDelete={handleDelete}
                  onUndo={undo}
                  onRedo={redo}
                  canUndo={canUndo}
                  canRedo={canRedo}
                  hasClipboard={!!clipboard}
                  selectedSubtitleId={selectedSubtitleId}
                  onSelectSubtitle={setSelectedSubtitleId}
                />
              </div>
              
              {/* Subtitle list column */}
              <div className="lg:col-span-1">
                <SubtitleList
                  subtitles={subtitles}
                  currentTime={currentTime}
                  onSeek={handleSeek}
                  onEdit={handleEditSubtitle}
                  onInsert={handleInsert}
                  onCopy={handleCopy}
                  onDelete={handleDelete}
                  selectedSubtitleId={selectedSubtitleId}
                  onSelectSubtitle={setSelectedSubtitleId}
                  onUndo={undo}
                  onRedo={redo}
                  canUndo={canUndo}
                  canRedo={canRedo}
                />
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Edit dialog */}
      <EditSubtitleDialog
        subtitle={editingSubtitle}
        isOpen={!!editingSubtitle}
        onClose={() => setEditingSubtitle(null)}
        onSave={handleSaveSubtitle}
      />

      {/* Auto generate dialog */}
      <AutoGenerateDialog
        isOpen={showAutoGenerate}
        onClose={() => setShowAutoGenerate(false)}
        mediaFile={mediaFile?.file || null}
        onSubtitlesGenerated={handleAutoGeneratedSubtitles}
      />

      {/* Translate dialog */}
      <TranslateDialog
        isOpen={showTranslate}
        onClose={() => setShowTranslate(false)}
        subtitles={subtitles}
        onTranslated={handleTranslated}
      />

      {/* Export video dialog */}
      <ExportVideoDialog
        isOpen={showExportVideo}
        onClose={() => setShowExportVideo(false)}
        videoFile={mediaFile?.file || null}
        videoUrl={mediaFile?.url || ''}
        subtitles={subtitles}
        subtitleStyle={subtitleStyle}
        duration={duration}
      />

      {/* Export subtitle dialog */}
      <ExportSubtitleDialog
        isOpen={showExportSubtitle}
        onClose={() => setShowExportSubtitle(false)}
        subtitles={subtitles}
        hasTranslation={hasTranslation}
      />

      {/* Settings dialog */}
      <SettingsDialog
        isOpen={showSettings}
        onClose={() => setShowSettings(false)}
      />
    </div>
  );
};

export default Index;
