import { useState, useRef, useCallback, useEffect } from 'react';
import { Header } from '@/components/Header';
import { UploadZone } from '@/components/UploadZone';
import { MediaPlayer, MediaPlayerRef } from '@/components/MediaPlayer';
import { SubtitleList } from '@/components/SubtitleList';
import { Timeline } from '@/components/Timeline';
import { EditSubtitleDialog } from '@/components/EditSubtitleDialog';
import { AutoGenerateDialog } from '@/components/AutoGenerateDialog';
import { TranslateDialog } from '@/components/TranslateDialog';
import { TextToSubtitleDialog } from '@/components/TextToSubtitleDialog';
import { ExportVideoDialog } from '@/components/ExportVideoDialog';
import { ExportSubtitleDialog } from '@/components/ExportSubtitleDialog';
import { SettingsDialog } from '@/components/SettingsDialog';
import { parseSubtitleFile, type Subtitle } from '@/lib/subtitleParser';
import { type TranslatedSubtitle } from '@/lib/translationService';
import { defaultSubtitleStyle, type SubtitleStyle } from '@/components/SubtitleStyleSettings';
import { useSubtitleHistory } from '@/hooks/useSubtitleHistory';
import { Download, Trash2, Wand2, Upload, Languages, Film, FileText, Settings, RefreshCw } from 'lucide-react';

// Function to split bilingual text (same as in other components)
function splitBilingualText(text: string): { original: string; translated: string } | null {
  const chineseRegex = /[\u4e00-\u9fa5]/;
  const englishRegex = /[a-zA-Z]/;

  if (chineseRegex.test(text) && englishRegex.test(text)) {
    // Pattern 1: Chinese text followed by English
    const pattern1 = /^([\u4e00-\u9fa5\s，。！？；：、""''（）【】]+)\s*([a-zA-Z\s,.'!?;:()"-]+)$/;
    const match1 = text.match(pattern1);
    if (match1) {
      return {
        original: match1[1].trim(),
        translated: match1[2].trim()
      };
    }

    // Pattern 2: English followed by Chinese
    const pattern2 = /^([a-zA-Z\s,.'!?;:()"-]+)\s*([\u4e00-\u9fa5\s，。！？；：、""''（）【】]+)$/;
    const match2 = text.match(pattern2);
    if (match2) {
      return {
        original: match2[2].trim(),
        translated: match2[1].trim()
      };
    }

    // Pattern 3: Try to split by sentence boundaries
    const sentences = text.split(/[.!?。！？]\s+/);
    if (sentences.length >= 2) {
      const firstPart = sentences[0];
      const secondPart = sentences.slice(1).join(' ');

      if (chineseRegex.test(firstPart) && englishRegex.test(secondPart)) {
        return {
          original: firstPart.trim(),
          translated: secondPart.trim()
        };
      } else if (englishRegex.test(firstPart) && chineseRegex.test(secondPart)) {
        return {
          original: secondPart.trim(),
          translated: firstPart.trim()
        };
      }
    }
  }

  return null;
}
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';

const Index = () => {
  const [mediaFile, setMediaFile] = useState<{ url: string; name: string; type: 'video' | 'audio'; file: File } | null>(null);
  const [subtitleFileName, setSubtitleFileName] = useState<string>('');
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  const [editingSubtitle, setEditingSubtitle] = useState<Subtitle | null>(null);
  const [showAutoGenerate, setShowAutoGenerate] = useState(false);
  const [showTranslate, setShowTranslate] = useState(false);
  const [showTextToSubtitle, setShowTextToSubtitle] = useState(false);
  const [showExportVideo, setShowExportVideo] = useState(false);
  const [showExportSubtitle, setShowExportSubtitle] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  // Load subtitle style from localStorage or use default
  const [subtitleStyle, setSubtitleStyle] = useState<SubtitleStyle>(() => {
    try {
      const saved = localStorage.getItem('subtitleStyle');
      if (saved) {
        const parsed = JSON.parse(saved);
        // Merge with default style to ensure all properties exist (for backward compatibility)
        return { ...defaultSubtitleStyle, ...parsed };
      }
    } catch (error) {
      console.warn('Failed to load subtitle style from localStorage:', error);
    }
    return defaultSubtitleStyle;
  });
  const [selectedSubtitleId, setSelectedSubtitleId] = useState<number | null>(null);
  const playerRef = useRef<MediaPlayerRef>(null);

  // Save subtitle style to localStorage whenever it changes
  useEffect(() => {
    try {
      localStorage.setItem('subtitleStyle', JSON.stringify(subtitleStyle));
    } catch (error) {
      console.warn('Failed to save subtitle style to localStorage:', error);
    }
  }, [subtitleStyle]);

  // Wrapper function to handle subtitle style updates
  const handleSubtitleStyleChange = useCallback((newStyle: SubtitleStyle) => {
    setSubtitleStyle(newStyle);
  }, []);

  // Reset subtitle style to default (for settings dialog)
  const handleResetSubtitleStyle = useCallback(() => {
    setSubtitleStyle(defaultSubtitleStyle);
  }, []);

  // Use subtitle history hook for undo/redo
  const {
    subtitles,
    setSubtitles,
    setSubtitlesWithoutHistory,
    resetHistory,
    undo,
    redo,
    canUndo,
    canRedo,
    clipboard,
    copySubtitle,
    pasteSubtitle,
    insertSubtitle,
    deleteSubtitle,
  } = useSubtitleHistory([]);

  // Check if subtitles have translations or mixed bilingual content
  const hasTranslation = subtitles.some(sub => {
    // Check for translatedText field
    if ('translatedText' in sub && sub.translatedText) {
      return true;
    }
    // Check for mixed bilingual text
    return splitBilingualText(sub.text) !== null;
  });

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      // Don't trigger shortcuts when typing in input fields
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) {
        return;
      }

      // Ctrl/Cmd + Z: Undo
      if ((e.ctrlKey || e.metaKey) && e.key === 'z' && !e.shiftKey) {
        e.preventDefault();
        undo();
      }
      // Ctrl/Cmd + Y or Ctrl/Cmd + Shift + Z: Redo
      if ((e.ctrlKey || e.metaKey) && (e.key === 'y' || (e.key === 'z' && e.shiftKey))) {
        e.preventDefault();
        redo();
      }
      // Ctrl/Cmd + C: Copy
      if ((e.ctrlKey || e.metaKey) && e.key === 'c' && selectedSubtitleId) {
        const sub = subtitles.find(s => s.id === selectedSubtitleId);
        if (sub) {
          e.preventDefault();
          copySubtitle(sub);
          toast.success('已复制字幕');
        }
      }
      // Ctrl/Cmd + V: Paste
      if ((e.ctrlKey || e.metaKey) && e.key === 'v' && clipboard) {
        e.preventDefault();
        pasteSubtitle(selectedSubtitleId ?? undefined);
        toast.success('已粘贴字幕');
      }
      // Delete or Backspace: Delete selected
      if ((e.key === 'Delete' || e.key === 'Backspace') && selectedSubtitleId) {
        e.preventDefault();
        deleteSubtitle(selectedSubtitleId);
        setSelectedSubtitleId(null);
        toast.success('已删除字幕');
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [undo, redo, copySubtitle, pasteSubtitle, deleteSubtitle, selectedSubtitleId, subtitles, clipboard]);

  const truncateFileName = useCallback((fileName: string, maxLength: number = 20) => {
    if (fileName.length <= maxLength) return fileName;

    const extension = fileName.split('.').pop();
    const nameWithoutExt = fileName.substring(0, fileName.lastIndexOf('.'));

    if (extension) {
      const availableLength = maxLength - extension.length - 3; // 3 for "..."
      if (availableLength > 0) {
        return `${nameWithoutExt.substring(0, availableLength)}...${extension}`;
      }
    }

    return `${fileName.substring(0, maxLength - 3)}...`;
  }, []);

  const handleMediaUpload = useCallback((file: File) => {
    const url = URL.createObjectURL(file);
    const type = file.type.startsWith('video') ? 'video' : 'audio';
    setMediaFile({ url, name: file.name, type, file });
    toast.success(`已加载: ${file.name}`);
  }, []);

  const handleReplaceMedia = useCallback((file: File) => {
    // Clean up old media URL
    if (mediaFile?.url) {
      URL.revokeObjectURL(mediaFile.url);
    }

    const url = URL.createObjectURL(file);
    const type = file.type.startsWith('video') ? 'video' : 'audio';
    setMediaFile({ url, name: file.name, type, file });

    // Reset playback state
    setCurrentTime(0);
    setDuration(0);
    setIsPlaying(false);

    toast.success(`已替换为: ${file.name}`);
  }, [mediaFile]);

  const handleSubtitleUpload = useCallback((file: File) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const content = e.target?.result as string;
      const parsed = parseSubtitleFile(content, file.name);
      resetHistory(parsed);
      setSubtitleFileName(file.name);
      toast.success(`已加载 ${parsed.length} 条字幕`);
    };
    reader.readAsText(file);
  }, [resetHistory]);

  const handleSeek = useCallback((time: number) => {
    playerRef.current?.seek(time);
    setCurrentTime(time);
  }, []);

  const handleEditSubtitle = useCallback((subtitle: Subtitle) => {
    setEditingSubtitle(subtitle);
  }, []);

  const handleSaveSubtitle = useCallback((updatedSubtitle: Subtitle) => {
    setSubtitles(prev =>
      prev.map(sub => sub.id === updatedSubtitle.id ? updatedSubtitle : sub)
    );
    toast.success('字幕已更新');
  }, [setSubtitles]);

  const handleAutoGeneratedSubtitles = useCallback((newSubtitles: Subtitle[]) => {
    resetHistory(newSubtitles);
    setSubtitleFileName('AI生成字幕');
  }, [resetHistory]);

  const handleSubtitleTimeChange = useCallback((id: number, startTime: number, endTime: number) => {
    setSubtitlesWithoutHistory(prev =>
      prev.map(sub => sub.id === id ? { ...sub, startTime, endTime } : sub)
    );
  }, [setSubtitlesWithoutHistory]);

  const handleInsert = useCallback((afterTime: number) => {
    insertSubtitle(afterTime);
    toast.success('已插入新字幕');
  }, [insertSubtitle]);

  const handleCopy = useCallback((subtitle: TranslatedSubtitle) => {
    copySubtitle(subtitle);
    toast.success('已复制字幕');
  }, [copySubtitle]);

  const handlePaste = useCallback((afterId?: number) => {
    if (clipboard) {
      pasteSubtitle(afterId);
      toast.success('已粘贴字幕');
    }
  }, [clipboard, pasteSubtitle]);

  const handleDelete = useCallback((id: number) => {
    deleteSubtitle(id);
    if (selectedSubtitleId === id) {
      setSelectedSubtitleId(null);
    }
    toast.success('已删除字幕');
  }, [deleteSubtitle, selectedSubtitleId]);

  const handleTranslated = useCallback((translatedSubtitles: TranslatedSubtitle[]) => {
    setSubtitles(translatedSubtitles);
  }, [setSubtitles]);

  const handleTextToSubtitleGenerated = useCallback((generatedSubtitles: Subtitle[]) => {
    setSubtitles(generatedSubtitles);
  }, [setSubtitles]);

  const handleClearAll = useCallback(() => {
    if (mediaFile?.url) URL.revokeObjectURL(mediaFile.url);
    setMediaFile(null);
    resetHistory([]);
    setSubtitleFileName('');
    setCurrentTime(0);
    setDuration(0);
    setIsPlaying(false);
    setSelectedSubtitleId(null);
    toast.info('已清除所有内容');
  }, [mediaFile, resetHistory]);

  return (
    <div className="min-h-screen bg-background">
      <Header onOpenSettings={() => setShowSettings(true)} />

      <main className="container mx-auto px-4 py-8 pb-20">
        {/* Upload Section */}
        {!mediaFile && (
          <div className="max-w-4xl mx-auto animate-fade-in mt-16">
            <div className="text-center mb-8">
              <h2 className="text-3xl font-bold gradient-text mb-2">开始创作</h2>
              <p className="text-muted-foreground">上传您的媒体文件和字幕，或使用AI自动生成</p>
            </div>

            <div className="grid md:grid-cols-2 gap-6">
              <UploadZone
                type="media"
                onFileSelect={handleMediaUpload}
                accept="video/mp4,video/webm,audio/mp3,audio/mpeg,audio/wav"
              />
              <UploadZone
                type="subtitle"
                onFileSelect={handleSubtitleUpload}
                accept=".srt,.vtt"
                currentFile={subtitleFileName}
              />
            </div>
          </div>
        )}

        {/* Editor Section */}
        {mediaFile && (
          <div className="animate-fade-in">
            {/* Action buttons */}
            <div className="flex flex-wrap items-center justify-between gap-4 mb-6">
              <div className="flex items-center gap-2">
                <span className="text-sm text-muted-foreground">正在编辑:</span>
                <span
                  className="px-3 py-1 rounded-lg bg-secondary text-foreground font-medium cursor-default max-w-[200px] truncate"
                  title={mediaFile.name}
                >
                  {truncateFileName(mediaFile.name)}
                </span>
                {/* Replace Media Button */}
                <label className="cursor-pointer">
                  <input
                    type="file"
                    accept="video/mp4,video/webm,audio/mp3,audio/mpeg,audio/wav"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleReplaceMedia(file);
                    }}
                    className="hidden"
                  />
                  <Button variant="ghost" size="icon" className="h-8 w-8 hover:bg-primary/20 hover:text-primary" asChild>
                    <span>
                      <RefreshCw className="w-4 h-4" />
                    </span>
                  </Button>
                </label>
              </div>

              <div className="flex items-center gap-2 flex-wrap">
                {/* AI Generate Button */}
                <Button
                  variant="default"
                  size="sm"
                  onClick={() => setShowAutoGenerate(true)}
                  className="gap-2 bg-gradient-to-r from-primary to-accent hover:opacity-90"
                >
                  <Wand2 className="w-4 h-4" />
                  AI 生成字幕
                </Button>

                {/* Translate Button */}
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowTranslate(true)}
                  disabled={subtitles.length === 0}
                  className="gap-2"
                >
                  <Languages className="w-4 h-4" />
                  翻译字幕
                </Button>

                {/* Upload subtitle */}
                <label className="cursor-pointer">
                  <input
                    type="file"
                    accept=".srt,.vtt"
                    onChange={(e) => {
                      const file = e.target.files?.[0];
                      if (file) handleSubtitleUpload(file);
                    }}
                    className="hidden"
                  />
                  <Button variant="outline" size="sm" className="gap-2" asChild>
                    <span>
                      <Upload className="w-4 h-4" />
                      上传字幕
                    </span>
                  </Button>
                </label>

                {/* Export Dropdown */}
                <DropdownMenu>
                  <DropdownMenuTrigger asChild>
                    <Button
                      variant="outline"
                      size="sm"
                      disabled={subtitles.length === 0 && mediaFile?.type !== 'video'}
                      className="gap-2"
                    >
                      <Download className="w-4 h-4" />
                      导出
                    </Button>
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end" className="w-48">
                    <DropdownMenuItem
                      onClick={() => setShowExportSubtitle(true)}
                      disabled={subtitles.length === 0}
                      className="gap-2"
                    >
                      <FileText className="w-4 h-4" />
                      导出字幕文件
                    </DropdownMenuItem>
                    <DropdownMenuItem
                      onClick={() => setShowExportVideo(true)}
                      disabled={mediaFile?.type !== 'video' || subtitles.length === 0}
                      className="gap-2"
                    >
                      <Film className="w-4 h-4" />
                      导出带字幕视频
                    </DropdownMenuItem>
                  </DropdownMenuContent>
                </DropdownMenu>

                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleClearAll}
                  className="gap-2 text-destructive hover:text-destructive"
                >
                  <Trash2 className="w-4 h-4" />
                  清除
                </Button>
              </div>
            </div>

            {/* Main editor layout */}
            <div className="space-y-4">
              {/* Top row: MediaPlayer and SubtitleList */}
              <div className="grid lg:grid-cols-3 gap-6 items-stretch">
                {/* Player - prioritize on mobile */}
                <div className="lg:col-span-2 order-1">
                  <MediaPlayer
                    ref={playerRef}
                    src={mediaFile.url}
                    type={mediaFile.type}
                    subtitles={subtitles}
                    currentTime={currentTime}
                    onTimeUpdate={setCurrentTime}
                    onDurationChange={setDuration}
                    isPlaying={isPlaying}
                    onPlayPause={() => setIsPlaying(!isPlaying)}
                    subtitleStyle={subtitleStyle}
                    onSubtitleStyleChange={handleSubtitleStyleChange}
                    hasTranslation={hasTranslation}
                  />
                </div>

                {/* Subtitle list - show after player on mobile */}
                <div className="lg:col-span-1 order-3 lg:order-2">
                  <SubtitleList
                    subtitles={subtitles}
                    currentTime={currentTime}
                    onSeek={handleSeek}
                    onEdit={handleEditSubtitle}
                    onInsert={handleInsert}
                    onCopy={handleCopy}
                    onPaste={handlePaste}
                    onDelete={handleDelete}
                    selectedSubtitleId={selectedSubtitleId}
                    onSelectSubtitle={setSelectedSubtitleId}
                    onUndo={undo}
                    onRedo={redo}
                    canUndo={canUndo}
                    canRedo={canRedo}
                    hasClipboard={!!clipboard}
                    onTextToSubtitle={() => setShowTextToSubtitle(true)}
                  />
                </div>
              </div>

              {/* Bottom row: Timeline - same width as MediaPlayer */}
              <div className="grid lg:grid-cols-3 gap-6 items-stretch">
                <div className="lg:col-span-2 order-2 lg:order-1">
                  <Timeline
                    subtitles={subtitles}
                    duration={duration}
                    currentTime={currentTime}
                    onSeek={handleSeek}
                    onSubtitleChange={handleSubtitleTimeChange}
                    onInsert={handleInsert}
                    onCopy={handleCopy}
                    onPaste={handlePaste}
                    onDelete={handleDelete}
                    onUndo={undo}
                    onRedo={redo}
                    canUndo={canUndo}
                    canRedo={canRedo}
                    hasClipboard={!!clipboard}
                    selectedSubtitleId={selectedSubtitleId}
                    onSelectSubtitle={setSelectedSubtitleId}
                  />
                </div>
                <div className="lg:col-span-1 order-4 lg:order-2">
                  {/* Image card */}
                  <div className="glass-card overflow-hidden h-40">
                    <img
                      src="/jiao.jpg?v=1"
                      alt="Jiao"
                      className="w-full h-full object-cover hover:scale-110 transition-transform duration-500 ease-in-out animate-pulse"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Edit dialog */}
      <EditSubtitleDialog
        subtitle={editingSubtitle}
        isOpen={!!editingSubtitle}
        onClose={() => setEditingSubtitle(null)}
        onSave={handleSaveSubtitle}
      />

      {/* Auto generate dialog */}
      <AutoGenerateDialog
        isOpen={showAutoGenerate}
        onClose={() => setShowAutoGenerate(false)}
        mediaFile={mediaFile?.file || null}
        onSubtitlesGenerated={handleAutoGeneratedSubtitles}
      />

      {/* Translate dialog */}
      <TranslateDialog
        isOpen={showTranslate}
        onClose={() => setShowTranslate(false)}
        subtitles={subtitles}
        onTranslated={handleTranslated}
      />

      {/* Text to subtitle dialog */}
      <TextToSubtitleDialog
        isOpen={showTextToSubtitle}
        onClose={() => setShowTextToSubtitle(false)}
        audioFile={mediaFile?.file || null}
        videoDuration={duration}
        existingSubtitles={subtitles}
        onGenerated={handleTextToSubtitleGenerated}
      />

      {/* Export video dialog */}
      <ExportVideoDialog
        isOpen={showExportVideo}
        onClose={() => setShowExportVideo(false)}
        videoFile={mediaFile?.file || null}
        videoUrl={mediaFile?.url || ''}
        subtitles={subtitles}
        subtitleStyle={subtitleStyle}
        duration={duration}
      />

      {/* Export subtitle dialog */}
      <ExportSubtitleDialog
        isOpen={showExportSubtitle}
        onClose={() => setShowExportSubtitle(false)}
        subtitles={subtitles}
        hasTranslation={hasTranslation}
        videoFileName={mediaFile?.name}
      />

      {/* Settings dialog */}
      <SettingsDialog
        isOpen={showSettings}
        onClose={() => setShowSettings(false)}
        onResetSubtitleStyle={handleResetSubtitleStyle}
      />

      {/* Footer */}
      <footer className="fixed bottom-0 left-0 right-0 border-t border-border/50 bg-background/90 backdrop-blur-sm z-10">
        <div className="container mx-auto px-4 py-4">
          <div className="text-center text-sm text-muted-foreground">
            Copyright © 2025 <a href="https://s1.hz001.tk/" target="_blank" rel="noopener noreferrer" className="text-primary hover:text-accent transition-colors underline">蓝色空间-AI 故事创作平台</a>. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Index;
