import { useState } from 'react';
import { Wand2, Loader2, Languages } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter, DialogDescription } from '@/components/ui/dialog';
import { transcribeAudio, extractAudioFromVideo } from '@/lib/transcriptionService';
import type { Subtitle } from '@/lib/subtitleParser';
import { toast } from 'sonner';

interface AutoGenerateDialogProps {
  isOpen: boolean;
  onClose: () => void;
  mediaFile: File | null;
  onSubtitlesGenerated: (subtitles: Subtitle[]) => void;
}

const LANGUAGES = [
  { code: 'auto', name: '自动检测' },
  { code: 'zho', name: '中文' },
  { code: 'eng', name: '英语' },
  { code: 'jpn', name: '日语' },
  { code: 'kor', name: '韩语' },
  { code: 'fra', name: '法语' },
  { code: 'deu', name: '德语' },
  { code: 'spa', name: '西班牙语' },
  { code: 'por', name: '葡萄牙语' },
  { code: 'rus', name: '俄语' },
  { code: 'ara', name: '阿拉伯语' },
];

export function AutoGenerateDialog({ isOpen, onClose, mediaFile, onSubtitlesGenerated }: AutoGenerateDialogProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [status, setStatus] = useState('');
  const [selectedLanguage, setSelectedLanguage] = useState('auto');

  const handleGenerate = async () => {
    if (!mediaFile) {
      toast.error('请先上传媒体文件');
      return;
    }

    setIsGenerating(true);
    setStatus('正在处理...');

    try {
      // Extract audio if it's a video file
      let audioFile = mediaFile;
      if (mediaFile.type.startsWith('video/')) {
        setStatus('正在提取音频...');
        audioFile = await extractAudioFromVideo(mediaFile);
      }

      const subtitles = await transcribeAudio(audioFile, selectedLanguage, setStatus);
      
      if (subtitles.length === 0) {
        toast.warning('未检测到语音内容');
      } else {
        toast.success(`成功生成 ${subtitles.length} 条字幕`);
        onSubtitlesGenerated(subtitles);
        onClose();
      }
    } catch (error) {
      console.error('Generation error:', error);
      toast.error(error instanceof Error ? error.message : '生成字幕失败');
    } finally {
      setIsGenerating(false);
      setStatus('');
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-[400px] bg-card border-border">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Wand2 className="w-5 h-5 text-primary" />
            <span className="gradient-text">AI 自动生成字幕</span>
          </DialogTitle>
          <DialogDescription className="text-muted-foreground">
            使用AI语音识别自动为您的媒体文件生成字幕
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <label className="text-sm font-medium text-foreground flex items-center gap-2">
              <Languages className="w-4 h-4 text-muted-foreground" />
              语言选择
            </label>
            <Select value={selectedLanguage} onValueChange={setSelectedLanguage}>
              <SelectTrigger className="bg-secondary/50 border-border">
                <SelectValue placeholder="选择语言" />
              </SelectTrigger>
              <SelectContent>
                {LANGUAGES.map((lang) => (
                  <SelectItem key={lang.code} value={lang.code}>
                    {lang.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <p className="text-xs text-muted-foreground">
              选择"自动检测"让AI自动识别语言
            </p>
          </div>

          {mediaFile && (
            <div className="p-3 rounded-lg bg-secondary/30 border border-border/50">
              <p className="text-sm text-muted-foreground">当前文件</p>
              <p className="text-sm font-medium text-foreground truncate">{mediaFile.name}</p>
            </div>
          )}

          {isGenerating && (
            <div className="flex items-center gap-3 p-4 rounded-lg bg-primary/10 border border-primary/20">
              <Loader2 className="w-5 h-5 text-primary animate-spin" />
              <div>
                <p className="text-sm font-medium text-foreground">{status || '处理中...'}</p>
                <p className="text-xs text-muted-foreground">这可能需要几分钟时间</p>
              </div>
            </div>
          )}
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={onClose} disabled={isGenerating}>
            取消
          </Button>
          <Button 
            onClick={handleGenerate} 
            disabled={isGenerating || !mediaFile}
            className="bg-primary hover:bg-primary/90 gap-2"
          >
            {isGenerating ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                生成中...
              </>
            ) : (
              <>
                <Wand2 className="w-4 h-4" />
                开始生成
              </>
            )}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
